### ISSUE TITLE
预设 QConfig 的 说明不正常

### ISSUE THREAD

**Issue by dc3671** [MegEngine/Documentation#122]
目前是直接来自 QConfig 类的 docstring。

建议修改为以下说明：

name | intro
-- | --
min_max_fakequant_qconfig | 一个使用 :class:`~.MinMaxObserver` 和 :class:`~.FakeQuant` 的预设 QConfig。
ema_fakequant_qconfig | 一个使用 :class:`~.ExponentialMovingAverageObserver` 和 :class:`~.FakeQuant` 的预设 QConfig。
sync_ema_fakequant_qconfig | 一个使用 :class:`~.SyncExponentialMovingAverageObserver` 和 :class:`~.FakeQuant` 的预设 QConfig。
ema_lowbit_fakequant_qconfig | 一个使用 :class:`~.ExponentialMovingAverageObserver` 和 :class:`~.FakeQuant` 且数值类型为 qint4 的预设 QConfig。
calibration_qconfig | 一个对激活值使用 :class:`~.HistogramObserver` 进行后量化（无 :class:`~.FakeQuant` ）的预设 QConfig。
tqt_qconfig | 一个使用 :class:`~.TQT` 进行假量化的预设 QConfig。
passive_qconfig | 一个使用 :class:`~.PassiveObserver` 和 :class:`~.FakeQuant` 的预设 QConfig。
easyquant_qconfig | 用于 ``easyquant`` 算法的 QConfig，等价于 ``passive_qconfig`` 。

**Comment by MegChai** [comment]
已经更新，请确认一下 ``FakeQuant`` 这个 class name 是否正确，应该是 module name ``fake_quant``  ?
