### ISSUE TITLE
官方文档教程里出现了不支持的用法T_T

### ISSUE THREAD

**Issue by MondayZhou** [MegEngine/Documentation#253]
在<https://github.com/MegEngine/Documentation/blob/206baa52805ff638fbece3380b8e2e9972292f0f/source/user-guide/tools/load-and-run.rst>里
出现了一个现在megengine不支持的语法：`mge.utils.load_tensor_binary`
全貌如下：
```python
import megengine as mge

v0 = mge.utils.load_tensor_binary('out/run0-var1602')
v1 = mge.utils.load_tensor_binary('out/run1-var1602')
```
### 报错
```python
AttributeError: module 'megengine.utils' has no attribute 'load_tensor_binary'
```
指路官方文档的位置：
<https://megengine.org.cn/doc/stable/zh/user-guide/tools/load-and-run.html>
- 正确性验证
    - dump输出结果

如果已经不支持了是否有新的替代的语句来读取输出结果？感谢帮助～

**Comment by MegChai** [comment]
文档已经更新 #253 ，该 Issue 将被关闭，如果有任何新问题可以开新 Issue 反馈。
