### ISSUE TITLE
增加 CompNode 的介绍文档

### ISSUE THREAD

**Issue by bealwang** [MegEngine/Documentation#258]
为了让用户深入理解 MegEngine 对计算设备的抽象，需要写一个 CompNode 的说明文档。阐述其基本作用，各种使用场景和预期效果。

**Comment by MegChai** [comment]
好耶 😆 ，但是这个事情之前不是 @xxr3376  说他有在写相关内容吗，有找到这篇文档的 Owner 吗？

**Comment by xxr3376** [comment]
我写了一半转交给 @genialwang 了，实在没空写了

**Comment by MegChai** [comment]
请 pull 最新的 ``main`` 分支，刚才添加了 `behind`目录，它将用于存放 《MegEngine 幕后揭秘》系列，形式上类似于解读风格的文章，可以用来专门存放与 MegEngine 有关的解释性质的内容，方便与 《MegEngine 架构设计》区分。

届时请在 ``Documentation/source/development/behind`` 下提供名为 ``comptnode.rst`` 的文件，并在里面编辑好用于 Review 的内容。

稍后会在开发者指南的 index 页面对各种分类属性进行说明，方便文档维护者了解生产内容应该存放在什么分类。
