### ISSUE TITLE
增加format的介绍文档

### ISSUE THREAD

**Issue by Beichen-Wang** [MegEngine/Documentation#262]
增加format的介绍文档，主要针对GPU的format，有：NCHW、NHWC、NCHW4、NCHW32、NCHW64、CHWN4。

**Comment by MegChai** [comment]
可以添加路径为 ``source/user-guide/model-development/tensor/format.rst`` 的文件，并在里面编写内容。Sphinx ReST 语法可参考 [Sphinx reStructuredText 语法入门](https://megengine.org.cn/doc/stable/zh/development/contribute-to-docs/restructuredtext.html) 页面，也可以先写出内容，后面再调整语法，

**Comment by Beichen-Wang** [comment]
好的

**Comment by Beichen-Wang** [comment]
> 可以添加路径为 `source/user-guide/model-development/tensor/format.rst` 的文件，并在里面编写内容。Sphinx ReST 语法可参考 [Sphinx reStructuredText 语法入门](https://megengine.org.cn/doc/stable/zh/development/contribute-to-docs/restructuredtext.html) 页面，也可以先写出内容，后面再调整语法，

好的
