### ISSUE TITLE
添加 CustomOp 的用户使用指南

### ISSUE THREAD

**Issue by cqchu** [MegEngine/Documentation#268]
展示 Custom Op 的基本抽象接口，告诉用户如何编写 Custom Op

**Comment by MegChai** [comment]
辛苦 & 感恩！请问 CustomOp 的设计文档现在定稿了吗，现在的文档结构可以考虑：

-  在用户指南中 工具篇 添加 CustomOp 使用文档 
  - 在 source/source/user-guide/tools 新建 customop.rst 文件并编写初稿
  - 完成初稿内容后提交 Pull Request 到 main 分支
- 在开发者指南 MEP 部分添加 CustomOp 设计文档（MEP 也可能需要花些时间 Review）

具体细节可以再交流。
