### ISSUE TITLE
希望支持megengine.where直接返回坐标

### ISSUE THREAD

**Issue by CVWangZH** [MegEngine/Documentation#294]
## 背景
从heatmap中取出大于阈值的坐标，尝试使用MegEngine算子[megengine.functional.where](https://megengine.org.cn/doc/stable/zh/reference/api/megengine.functional.where.html?highlight=where#megengine.functional.where)但是不支持直接返回坐标，比如有x和y（对齐np.where和torch.where可以直接返回坐标）。没有找到其他合适的算子。

## 任务描述
megengine.functional.where 希望支持可以不传入x, y，仅传入condition，直接返回符合条件的坐标。或者是否有满足以上需求的算子

## 目标
megengine.where对齐np.where和torch.where

**Comment by MegChai** [comment]
相关文档页面已经更新 #295 .

![image](https://user-images.githubusercontent.com/21091736/140052385-7a7844b8-94f0-4b9c-a143-2d652529a504.png)
