### ISSUE TITLE
MegEngine 教程（Tutorials）征集

### ISSUE THREAD

**Issue by MegChai** [MegEngine/Documentation#30]
目前预计结构，还待完善：

-  [x] 天元 MegEngine 快速上手 （快速展示 API）

## 深度学习零基础 LEARNING-BY-DOING

这一部分面向绝对零基础的 Python 用户，不打算分模块，而是 i + 1 任务式讲解。

-  [x] 天元 MegEngine 基础概念：张量/算子/计算图/求导器/优化器/损失函数
-  [x] 一个稍微复杂些的线性回归模型：数据集基本概念/Dataloader/Sampler/梯度下降
-  [x] 从线性回归到线性分类：不同的机器学习任务类型/理解图像数据
-  [x] 从感知机到深度神经网络：funtional 和 module/模型保存和加载
-  [x] 神经网络训练技巧：...
-  [x] 炼丹并不是深度学习的全部：普及推理部署相关的概念，实际教程放在“用户指南”

这一部分的教程对于有经验的用户来说会显得有些啰里八嗦的，但重点在于培养直觉和思维。

## 趣味教程

打算在这放一些有意思的 DEMO 案例，带图片，主要是吸引用户兴趣。

**Comment by hamsterqx** [comment]
可以从有趣味的检测，追踪开始做趣味性demo
比如
检测：3D检测或者人体关节点检测，可视化比较有趣
追踪：单目标追踪，可以追踪手等部件的追踪互动demo
可以参考：https://mediapipe.dev/

**Comment by bigeagle** [comment]
Learning to Paint: https://github.com/megvii-research/ICCV2019-LearningToPaint
Neural Painter: https://github.com/megvii-research/neural-painter

**Comment by MegChai** [comment]
有人反馈说希望提供 CS230 231n 224n 的 MegEngine 版本，以及最近比较火的 MIT 6.S191 课程。

**Comment by MegChai** [comment]
Refs: https://github.com/MegEngine/MegEngine/issues/162

**Comment by MegChai** [comment]
#82  需要添加 Hub 相关的文档

**Comment by pongvista** [comment]
张量吧？而不是【张亮】

**Comment by MegChai** [comment]
> 张量吧？而不是【张亮】

改正过来了，这个 Issue 过于久远了，如果有新的想法可以考虑新开一个 Issue 或者 Pull Requset.
