### ISSUE TITLE
讨论：我们是否需要一个模型训练的首页

### ISSUE THREAD

**Issue by xxr3376** [MegEngine/Documentation#342]
经过指导几位不太了解 MegEngine 或 PyTorch 的朋友学习 megengine，发现疑似缺失一个“最小可用样例”，导致被指导的人只能不断的询问“我需要做什么？“，然后我来粘贴对应的 Module 或者 Optimizer 的讲解页面给他。

由此，我有一个想探讨的 idea：我们是否需要一个模型训练的首页页面？

在这个页面上，估计可以展示以下内容：

* 训练需要了解的最少知识，了解有哪几个级别模块（似乎只需要知道 module 定义模型、optimizer 优化就已经大概够了？）
* 提供一个最小化的样例，便于用户能在2分钟内真的把代码 run 起来
* 提供一些 link，让用户知道当希望扩展样例功能的时候，可以先看哪些东西？

**Comment by MegChai** [comment]
快速上手：https://megengine.org.cn/doc/stable/zh/getting-started/quick-start.html 页面能够解决问题吗

**Comment by xxr3376** [comment]
@MegChai  看起来内容是非常符合这个诉求的，不过我之前一直在用户指南里到处寻找，所以怎么也找不到

**Comment by MegChai** [comment]
> @MegChai 看起来内容是非常符合这个诉求的，不过我之前一直在用户指南里到处寻找，所以怎么也找不到

新用户第一次访问 MegEngine 文档看到的应该是这个页面：https://megengine.org.cn/doc/stable/zh/index.html

所以默认初学者会先看 《新手入门》 中的内容。

--------------

P.S: 如果是更加初级的新手，可以看《 [MegEngine 深度学习入门教程](https://megengine.org.cn/doc/stable/zh/getting-started/beginner/intro.html) 》，不过这整个教程最近正在以缓慢的速度迭代到下一版，所以衔接处可能会很有问题。

**Comment by xxr3376** [comment]
@MegChai 我这次遇到的情况，用户心中抱着的更多是“我希望尽快能快的弄出一份可运行的代码”（而这是个常态），这个和你提到的入门教程的目的不是很符合。

**Comment by MegChai** [comment]
> @MegChai 我这次遇到的情况，用户心中抱着的更多是“我希望尽快能快的弄出一份可运行的代码”（而这是个常态），这个和你提到的入门教程的目的不是很符合。

OK. 我感觉对于国内用户，获取 MNIST 数据集可能反而容易成问题。可以问问是不是遇到了棘手的情况。

**Comment by xxr3376** [comment]
@MegChai 目前没遇到（因为用户根本没用这个教程，心急…）
