### ISSUE TITLE
废弃api 需要加一下 替代api , 例如tensor.set_value

### ISSUE THREAD

**Issue by Beichen-Wang** [MegEngine/Documentation#405]
废弃api 需要加一下 替代api , 例如tensor.set_value

**Comment by MegChai** [comment]
要不要试着提个 PR，直接修改 [这个文件](https://github.com/MegEngine/Documentation/blob/main/source/reference/deprecated.rst)

**Comment by Beichen-Wang** [comment]
好的 已提
