### ISSUE TITLE
文档 LITE API 参考页面与源码内容不一致

### ISSUE THREAD

**Issue by colorjam** [MegEngine/Documentation#455]
## 环境
1.系统环境：MacOS
2.MegEngine版本：master 分支，应该是最新的 v.1.9.1
3.python版本：3.7

## 复现步骤

源代码 lite/common_enum_c.h 中枚举的 LiteDeviceType 和文档不一致 https://www.megengine.org.cn/doc/stable/en/reference/lite/common.html#_CPPv414LiteDeviceType

**Comment by MegChai** [comment]
@colorjam  您好，此版本文档 LITE API 展示有误，确实与 GitHub 开源出的源码存在不一致，感谢您指出，预计今日内进行修复。

**Comment by MegChai** [comment]
LITE API 文档页面已经更新，再次为给您造成的困惑表示歉意...

![image](https://user-images.githubusercontent.com/21091736/177296565-b0bab882-d482-488c-b489-8fb73424af38.png)
