### ISSUE TITLE
选择正确的 resnet 文件版本

### ISSUE THREAD

**Issue by MegChai** [MegEngine/Documentation#47]
https://github.com/MegEngine/Documentation/blob/c85879bed08466ca9851e2db5c387bf6f8b8fcef/examples/models/resnet.py#L807

可以从上面这个文件看出这是由于解冲突格式不正确导致的两版文件并存， @Qsingle 请判断一下上面和下面的两个版本哪一个是需要保留的。

**Comment by Qsingle** [comment]
==== 上方的版本需要保留，感谢
