### ISSUE TITLE
是否基于《动手学深度学习》中文第二版预览版发布，做一个MegEngine版本做推广

### ISSUE THREAD

**Issue by TUT-jiayou** [MegEngine/Documentation#53]
如题
https://zhuanlan.zhihu.com/p/355739259

**Comment by MegChai** [comment]
MegEngine 文档目前发布了一版《[MegEngine 深度学习入门教程](https://megengine.org.cn/doc/stable/zh/getting-started/beginner/intro.html)》，与 《动手学深度学习》的定位有一些不一样。后续还将围绕着 MegEngine 的其它功能，发布 E2E 的系列教程。此 Issue 将被关闭，如果有其它新的建议或意见，欢迎在新的 Issue 中反馈~
