### ISSUE TITLE
增加“点赞”功能

### ISSUE THREAD

**Issue by bigeagle** [MegEngine/Documentation#78]
感觉很多地方写的很棒，但是没有地方点赞👍。
众所周知，点赞👍人类的基本需求，所以有没有办法在页面上加个点赞👍功能？

**Comment by MegChai** [comment]
对于静态网页要实现这样的功能可能要引入第三方...

确实在考虑如何增加类似的功能：能够快速地针对单个页面进行反馈，然后跳转到 论坛或者 Issue bla bla

**Comment by MegChai** [comment]
既然都要做点赞功能了，就直接加了个 online chat 在网页端，欢迎体验～
