### ISSUE TITLE
量化API未更新到1.3版

### ISSUE THREAD

**Issue by bigeagle** [MegEngine/Documentation#80]
如题，量化部分仍然是 1.2 的 API，需要更新一下。

我如果有时间就PR。

**Comment by MegChai** [comment]
👏  欢迎 PR ~ 目前的 API 采用的是手动组织的策略，https://github.com/MegEngine/Documentation/blob/main/source/reference/quantization.rst 这个文件是主观组织的，欢迎改成最符合用户使用方法的形式。

**Comment by MegChai** [comment]
“API 未更新” 好像是因为之前看的是某过时的内部版本文档，现在类似 QParams 这样的 API 已经加进来咯，

**Comment by bigeagle** [comment]
```def fake_quant_tensor(inp: Tensor, qmin: int, qmax: int, q_dict: Dict) -> Tensor:```
比如这个就还没更新呢
