### ISSUE TITLE
希望添加Hub的文档

### ISSUE THREAD

**Issue by Randolph87xxx** [MegEngine/Documentation#82]
加载预训练权重的需求比较常见，希望在文档增加Hub相关的文档方便查找

**Comment by MegChai** [comment]
得请 @zhouyizhuang-megvii 来讨论一下，相关内容在 Hub 的 readme 和 models 中都有提，有没有比较合适的形式在用户指南中提一下怎么用（是否需要具体的 example 还是链接到 Hub 那边）。如果只是在 API 中暴露 Hub 接口，确实有些单一。

**Comment by MegChai** [comment]
![image](https://user-images.githubusercontent.com/21091736/144193267-0d0f2de6-30aa-4fed-b1e5-2049bc4bcd05.png)


Done in  #305.
